import { writeFile, mkdir } from 'fs/promises';
import { dirname, resolve } from 'path';

export async function writeReport(
  content: string,
  outputPath: string,
  title = 'AI Review Report',
): Promise<string> {
  const resolvedPath = resolve(process.cwd(), outputPath);
  const dir = dirname(resolvedPath);

  await mkdir(dir, { recursive: true });

  const timestamp = new Date().toISOString();
  const header = `<!-- Generated by DevX CLI at ${timestamp} -->\n`;
  const finalContent = content.startsWith('#') ? header + content : `${header}# ${title}\n\n${content}`;

  await writeFile(resolvedPath, finalContent, 'utf-8');
  return resolvedPath;
}
